name: refried_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  geolocator: ^13.0.2
  intl: ^0.19.0
  geocoding: ^3.0.0
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
